name: devfin
description: Devfin - Real-time financial news, markets data and investing analysis
version: 1.0.0+1
repository: https://github.com/huykgit98/devfin
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  # local packages
  authentication_repository:
    path: packages/authentication_repository
  form_inputs:
    path: packages/form_inputs


  #external packages
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  floating_draggable_widget: ^2.1.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  fl_chart: ^0.66.2
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.2
  flutter_native_splash: ^2.3.9
  scrollable_positioned_list: ^0.3.8
  scroll_to_index: ^3.0.1
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.9
  google_fonts: ^6.1.0
  drag_and_drop_lists: ^0.3.3
  firebase_core: ^2.24.2
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.7.0
  easy_refresh: ^3.3.4
  extended_nested_scroll_view: ^6.2.1
  vertical_scrollable_tabview: ^0.1.1
  equatable: ^2.0.5
  formz: ^0.6.1
  get_it: ^7.6.7
  injectable: ^2.3.2
  smooth_sheets: ^0.2.0
  flutter_platform_widgets: ^6.1.0
  animated_bottom_navigation_bar:
    git:
      url: https://github.com/huykgit98/animated-bottom-navigation-bar-flutter.git
      ref: 22ec10a85c3b3d548c546cc065f3e5a7f30fa17c

dev_dependencies:
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  injectable_generator: ^2.4.1
  bloc_test: ^9.1.4
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  generate: true

flutter_gen:
  output: lib/app/config/gen/

flutter_native_splash:
  color: '#ffffff'
#  image: assets/icons/app_icon_transparent_bg.png
#  color_dark: '#000000'
#  image_dark: assets/icons/app_icon_dark_theme_transparent_bg.png
